services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persist database data even if container is removed

  backend:
    build: ./backend
    container_name: space2study-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URL=${MONGO_DB_URL} # Connect to the mongodb service container
    depends_on:
      - mongodb # Ensure database is ready before backend starts

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE_PATH=${API_URL} # Pass API URL to frontend build
    container_name: space2study-frontend
    ports:
      - "${FRONTEND_PORT}:80" # Map host port 3000 to Nginx container port 80
    depends_on:
      - backend

volumes:
  mongo-data: # Define named volume for data persistence