apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- backend-configmap.yml
- backend-deployment.yml
- backend-service.yml
- frontend-deployment.yml
- frontend-service.yml
- mongodb-pvc.yml
- mongodb-deployment.yml
- mongodb-service.yml
- ingress.yml
- middleware-strip-api.yml
