x-restart: &default-restart
  restart: always

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-deploy-small: &deploy-small
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 256M

x-deploy-micro: &deploy-micro
  deploy:
    resources:
      limits:
        cpus: '0.1'
        memory: 100M

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    <<: [*default-restart, *deploy-small]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v3.0.0
    <<: [*default-restart, *deploy-small]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "app-node:${APP_NODE_IP}"
      - "cicd-node:${CICD_NODE_IP}"
      - "runner-node:${RUNNER_NODE_IP}"
    depends_on:
      - cadvisor
    logging: *default-logging

  grafana:
    image: grafana/grafana:11.0.11
    <<: [*default-restart, *deploy-small]
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    logging: *default-logging

  loki:
    image: grafana/loki:3.0.0
    <<: [*default-restart, *deploy-small]
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
  
  promtail:
    image: grafana/promtail:3.0.0
    <<: [*default-restart, *deploy-micro]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    logging: *default-logging

volumes:
  prometheus-data:
  grafana-storage:
  loki-data: