---
- import_tasks: base.yml
- import_tasks: k3s.yml
- import_tasks: kubeconfig.yml
- import_tasks: manifests.yml
- import_tasks: secrets.yml
- import_tasks: monitoring.yml
- import_tasks: deploy.yml
