global:
  scrape_interval: 30s
  scrape_timeout: 25s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'app-monitor-node'
  static_configs:
  - targets: [ 'cadvisor:8080' ]
    labels:
      instance: 'app-monitor-node:8080'

- job_name: 'cicd-node'
  static_configs:
  - targets: [ 'cicd-node:8080' ]
