FROM jenkins/inbound-agent:3345.v03dee9b_f88fc-2-jdk17

USER root

RUN apt-get update && \
    apt-get install -y docker.io curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins